### ISSUE TITLE
Additional small efficiency changes to the app

### ISSUE THREAD

**Issue by celtson** [CIS-412-Spring-2015/frontend#100]
- [ ] Condense the functions that make the previous and next buttons work. 
- [x]  Make sure the Staff Pill is highlighted whenever the Create New Report is clicked
- [ ] Make the Next and Previous buttons disappear when on the Submit page
- [ ] Make the Previous button disabled when on the Staff tab and the next button disabled when on the Submit tab 
- [ ] Make the item-listing template and the ministry-footer template one file instead of splitting it into two by adding an if or unless statement for when the footer shows up.

**Comment by neongreenfruit** [comment]
Calling this void and closing this issue!
