### ISSUE TITLE
Make the Cancel Button go to In Progress page

### ISSUE THREAD

**Issue by celtson** [CIS-412-Spring-2015/frontend#101]
- [x] when you click cancel it takes you back to the In Progress Page.

This is how it works in all the rest of the application

**Comment by neongreenfruit** [comment]
Can we talk about this? I'm not sure I would worry too much about this button, I think that this goes along with something else that @mdfrederick and I don't think we need to worry about quite yet. #95

**Comment by devfreddy** [comment]
I'd argue that for this particular module it isn't needed but, for consistency's sake I'd say go ahead and implement this. Most of the other Modules follow this convention when creating a new object.
