### ISSUE TITLE
Fix my Hospital Run

### ISSUE THREAD

**Issue by JDGillespie** [CIS-412-Spring-2015/frontend#105]
As a developer I need to fix my hospital run so that I can continue to work.
- [ ] Figure out glob error
- [x] Have Hospital Run working!!! 9 hours

![nodesass](https://cloud.githubusercontent.com/assets/9558693/6836839/56952834-d31c-11e4-9bce-ae30088bd06f.png)

**Comment by neongreenfruit** [comment]
I emailed @jkleinsc and @mdfrederick about this problem. I'm hoping we can come to some conclusion before the end of sprint, but it's kind of my fault that we have this issue at all! (@nejmeh)

**Comment by jkleinsc** [comment]
@TheFrontGuy try doing the following
1) Delete all of the files in node_modules
2) run the command: npm cache clean
3) run the command: npm install

**Comment by JDGillespie** [comment]
![error](https://cloud.githubusercontent.com/assets/10821108/6839571/d271e996-d340-11e4-83a8-2b664ac185b6.png)
This is the current message I get when I try to run ember serve

**Comment by jkleinsc** [comment]
Did you follow the steps I listed?

**Comment by JDGillespie** [comment]
yes, npm installed fine.

**Comment by JDGillespie** [comment]
also, now I cannot seem to get into couch...

**Comment by jkleinsc** [comment]
What output do you get when you run the command: ember -v

**Comment by JDGillespie** [comment]
ember -v gives:
version: 0.1.4
Could not find watchman, falling back to NodeWatcher for file system events
node: 0.10.3
npm: 2.1.10

**Comment by jkleinsc** [comment]
@TheFrontGuy I found the problem and it has been fixed.  You will need to do the following:
1) Get the latest from github
2) Delete all of the files in node_modules
3) run the command: npm install

**Comment by JDGillespie** [comment]
Im am now able to get onto hospital run, but now I can login.

**Comment by JDGillespie** [comment]
![login error](https://cloud.githubusercontent.com/assets/10821108/6906874/8c072be8-d6ff-11e4-91fe-cec072b29e2a.png)
Noticed this when trying I tried to log into hospital run

**Comment by neongreenfruit** [comment]
This means that couch isn't running
