### ISSUE TITLE
Validation for CE

### ISSUE THREAD

**Issue by JDGillespie** [CIS-412-Spring-2015/frontend#144]
As a developer, I need to validate the inputs for the CE part of Faith Declarations.
- [x] CE validates inputs 6 hours

[Projected End State](https://docs.google.com/document/d/1oP6ac4NwjyaKEYOJu3hCSPKQQd2NZdTcmlk_5o9oyIQ/edit?usp=sharing): 3.5

**Comment by JDGillespie** [comment]
@jkleinsc how are you doing validation for forms outside of required (for example: price in /pricing/edit/new)?

**Comment by jkleinsc** [comment]
Validations are done using ember validations: https://github.com/dockyard/ember-validations  Please look at that link for how to define validations and as to what types of validations are possible.

You define the validations in the model (eg app/model/pricing.js) and then the way HospitalRun is setup validation should happen automatically (it will mark fields as invalid when you tab/focus away from them and the update/add button will be disabled until all validation has been passed).

For reference here's the validation defined for pricing:

```
    validations: {
        category: {
            presence: true //Field just needs a value
        },
        name: {
            presence: true //Field just needs a value
        },        
        price: {
            numericality: true //Field must be a number
        }
    }
```
