### ISSUE TITLE
leadership event is causing em-text database issues

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#174]
something is wrong with how em-text is showing data
- [X] test when em-text breaks down

Currently only breaks with addition of participants there's another issue for that.

**Comment by zmarkle** [comment]
after messing around with this for a while I've narrowed it down to something that has to do with when a participant is added to the event page. Leadership and Community add function fine and cause no issue. At least that's the way its going on my machine.

**Comment by neongreenfruit** [comment]
well I will test it, if it's still broken then we will just not be talking about leadership events
