### ISSUE TITLE
Learn Tech Stack - Brandon Maze

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#26]
- [x] Get Technology Stack working 
- [x] Download Ember Inspector from the Chrome Web Store
- [x] Show that on your computer HospitalRun works
- [x] Add your name to the Reports Archive (index) Template file in a paragraph tag to show that you have looked through the code, and have the tech stack working. 
- [x] Push changes up to server. (please make sure that your code it not broken!)

**Comment by BMaze** [comment]
Closing Issue

**Comment by BMaze** [comment]
4.5 hours
