### ISSUE TITLE
Learn Tech Stack - Zach Markle

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#27]
- [x] Get Technology Stack working 
- [x] Download Ember Inspector from the Chrome Web Store
- [x] Show that on your computer HospitalRun works
- [x] Add your name to the Reports Archive (index) Template file in a paragraph tag to show that you have looked through the code, and have the tech stack working. 
- [x] Push changes up to server. (please make sure that your code it not broken!)

**Comment by zmarkle** [comment]
Finally have ember server running and Hospital Run loaded.

**Comment by neongreenfruit** [comment]
please add your hours to this and then close the issue thanks!

**Comment by zmarkle** [comment]
I put in about 4 hours of work getting everything working and doing the other bits.
