### ISSUE TITLE
Tab - Additional Info

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#3]
- [x] Create a view
- [x] Three Tabs 
  
  | Ministry Results | Recommendations/Needs | Other Significant Items |
  | --- | --- | --- |
  | 3000 Word Text Entry Field | 3000 Word Text Entry Field | 3000 Word Text Entry Field |
- [x] Save Each Tab's Data
- [x] Validate Data

**Comment by neongreenfruit** [comment]
@ct1221 this needs to stay in the whole project scope milestone, please create new tasks for each part of this page in the module!

**Comment by kp1251** [comment]
@ct1221 @TheFrontGuy I closed the issue since it seems like, from looking at the additional info view in Hopsitalrun, this issue is finished... open it back up if I am wrong.
