### ISSUE TITLE
Summary Sheet View Creation - Initial

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#31]
As a developer, I need to create a view of the Summary tab so that others can understand the design and layout of the Summary tab.
- [x] Look into how the module has been created thus far 1hr
- [x] Look through the existing code to learn the conventions 2hrs 15mins
- [x] Create a view that shows up when someone clicks the 'Summary' Tab Under the 'New Report'/'In Progress Report' section of the module. 6hrs 45mins

Referencing Issue(s): #13, #15, #16, #17, #18, #19, #21

**Comment by Falconvaulter** [comment]
Removed {{label="Totals"}} because it caused the build to fail
