### ISSUE TITLE
Leadership Events View Creation - Initial

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#33]
- [ ] Look into how the module has been created thus far
- [ ] Look through the existing code to learn the conventions
- [ ] Create a view that shows up when someone clicks the 'Leadership' Tab Under the 'New Report' section of the module.

Referencing Issue: #9

**Comment by Benning-k** [comment]
Duplicate, no longer relevant.

**Comment by BMaze** [comment]
redundant
