### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by neongreenfruit** [CIS-412-Spring-2015/frontend#4]
As a Cure Intern I need to get a base Ministry Module existing, so that when the team begins to work, there is something in place for them to build off of.
- [x] Sub-Navigation in report (tabs??)
  - Copy New Patient Formatting (peter did this, still tweaking this)
  - Celtson added more sub navigation!
- [x] Work through the top level navigation bar - **2 hours**
- [x] Set up Ministry Model - **10 hours**

**Comment by neongreenfruit** [comment]
**Top Level Navigation Links** (idea?)
- Hospital
- Leadership
- Community
- Christianity Explored
- Faith Declarations
- Demographics
- Additional Info
- Summary (this will be the submission page)
- (possibly) have a submit button at the top of the page that validates just like it should

---

There should also be arrows to go forward and back through the pages. [Right](https://octicons.github.com/icon/chevron-right/) and [Left](https://octicons.github.com/icon/chevron-left/)

**Comment by neongreenfruit** [comment]
This task is finished, I think it's time to pass a lot of this stuff on to the teams. @Falconvaulter let me know your thoughts! Thanks!

**Comment by Falconvaulter** [comment]
I agree @neongreenfruit we should start looking at what tasks are ready for Sprint 2, and what else needs to be set up for that.

**Comment by neongreenfruit** [comment]
ok! I'm going to close this issue!
