### ISSUE TITLE
Organization of information in database

### ISSUE THREAD

**Issue by JDGillespie** [CIS-412-Spring-2015/frontend#49]
- [ ] Save the information to the database
- [ ] Be able to view all names that are in the database
- [ ] Be able the edit the names in the database

Referencing Issue: #20

**Comment by Falconvaulter** [comment]
I don't think this issue will be able to be completed in sprint 2. In order to save the information and have it load in the list it will need to be linked to a report ID, which will not exist until Sprint 2 is completed

**Comment by JDGillespie** [comment]
not needed
