### ISSUE TITLE
Faith Declaration UI Structure

### ISSUE THREAD

**Issue by celtson** [CIS-412-Spring-2015/frontend#56]
As a developer I want to be able to navigate the Faith Declaration UI design, so that buttons display views as they should and that all believers information can be edited. 
- [x] Make sure Add New Convert button appears and it creates a general information view. -3hr
- [x] Make sure Cancel and Save button appears - 30min
- [x] Current believers are shown under the initial view under the faith declaration tab. - 2hr & 30min
- [x] Make Hide and Show Believer button appears and functions to show and hide believers. -2hr
- [x] Hospital Run Demo has everything

Referencing Issue #20

**Comment by Falconvaulter** [comment]
This task will not be possible for this sprint. You will need a report to save the believers to, and the ID for the reports don't exist yet. Maybe move to sprint 3?

**Comment by celtson** [comment]
Yea I thought about that, I will be able to do some hard coding that should allow me to complete some aspects of this story. I will avoid database parts of the task.
