### ISSUE TITLE
Summary Sheet Design Document

### ISSUE THREAD

**Issue by kp1251** [CIS-412-Spring-2015/frontend#64]
As a UI Designer, I need to write a  document about the design of the summary tab so that I can show others the design and layout of the summary tab as well as create a user-friendly design for doctors.
- [x] Write a design document for the Summary tab 6hrs 30mins
- [x] Submit the document on Google Drive in the Cure folder 4mins

**Comment by neongreenfruit** [comment]
One comment for you on your BEAUTIFUL design document, we will need the ability to add data for most of your tabs. I think that the graph thing will be great for the totals page, but not for the rest of the pieces of your tab (ALSO you probably shouldn't have separate tab navigation under your tab, I'm afraid that will get too confusing, but we can talk about it) I hope this doesn't come across as anything other than a help! Everything does look great though!

**Comment by kp1251** [comment]
I recreated the summary sheet design doc by mostly making the changes that Rebekah suggested. The new as well as the old design docs are in the Cure folder and I added 2 hours that I spent creating the new design doc to this issue.
