### ISSUE TITLE
Next and Back Button Functionality

### ISSUE THREAD

**Issue by celtson** [CIS-412-Spring-2015/frontend#86]
As a UI developer I want to be able to add functionality and design to next and back buttons, so that when the user clicks on either, the respective view is shown. 
- [x] Make sure when the next button is clicked, the next view is seen - 2hrs
- [x] Make sure when the previous button is clicked, the previous view is seen - 2hrs
- [x] Make sure the focus goes on whichever tab is seen. - 2hrs
- [x] Add a ministry footer panel that includes, save, cancel, next and previous buttons - 1hr
- [x] Make sure Next and Previous buttons do not show up on Submit page - 1hr 30min
- [x] Learn how link-to handlebar works 
- [x] Make sure the first tab is seen on load - 30min

**Comment by neongreenfruit** [comment]
Hey you probably know this but the submit page doesn't need the previous and back button. I haven't looked into the code but I thought I'd put something in here.

**Comment by celtson** [comment]
haha yup! I was trying to figure out how to not allow the footer panel to show on the submit page. The only thing I figured out so far was to not allow it to be connected to the same panel as the others pages. (Can explain in class tomorrow :) )

**Comment by neongreenfruit** [comment]
It looks great! Thanks! I can't wait to hear about it!

**Comment by neongreenfruit** [comment]
I emailed you but I wanted to put a comment in here, there is something causing this great thing to show up in every part of HospitalRun, we need to fix that, THANKS! 
![screen shot 2015-03-24 at 9 34 18 am](https://cloud.githubusercontent.com/assets/9558693/6802707/f998154c-d208-11e4-91b6-3d41e0cca71e.png)
I also don't believe we want it showing up before a tab is clicked, is that correct?
