### ISSUE TITLE
Research Couchdb

### ISSUE THREAD

**Issue by zmarkle** [CIS-412-Spring-2015/frontend#97]
As a developer I need to understand how couchdb work and interacts with hospital run so that I will be able to build the functionality of any view.
- [x] look into how Couchdb works.  2 hours  30 minutes
- [x] Keep track of links so the info gather can be used later.
- [x] Examine our current Couchdb. 1 hour  30 minutes
- [x] Look at ember code to see how it interacts with the database. 1 hour
- [x] Write up a doc of understandings 1 hour

https://docs.google.com/a/messiah.edu/document/d/1aDNATGLMPh6DBgng7eCg4e60DzUnSBFP9SKkcq7ieFo/edit?usp=sharing

**Comment by neongreenfruit** [comment]
Will this include a research document?

**Comment by zmarkle** [comment]
It should I just didn't get around to filling in the check boxes, because i had to stop writing and move to something else quickly. I apologize for not filling it in sooner.
